language: node_js
cache:
 directories:
  - node_modules
notifications:
  email: false
node_js:
 - '8.1'
branches:
 except:
  - /^v\d+\.\d+\.\d+$/
before_script:
 - chmod 0777 ./node_modules/.bin/tsc
 - chmod 0777 ./node_modules/.bin/protractor