language: node_js
notifications:
  email: false
node_js:
 - '8.0'
 - '8.1'
 - '8.2'
 - '9.0'
branches:
 except:
  - /^v\d+\.\d+\.\d+$/
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - chmod 0777 ./node_modules/.bin/tsc
 - chmod 0777 ./node_modules/.bin/protractor
