language: node_js
cache:
 directories:
  - node_modules
notifications:
  email: false
node_js:
 - '8.0'
 - '8.1'
 - '8.2'
 - '9.0'
branches:
 except:
  - /^v\d+\.\d+\.\d+$/
before_script:
 - ./node_modules/.bin/tsc
 - ./node_modules/.bin/protractor