language: node_js
notifications:
  email: false
node_js:
 - '7'
branches:
 except:
  - /^v\d+\.\d+\.\d+$/
sudo: required
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  travis encrypt SAUCE_USERNAME=DIEGOCARDENAS --add
  travis encrypt SAUCE_ACCESS_KEY=a5085cc8-9fc5-4856-a2d4-bc12e86e6664 --add
